const PREFIX = "RegisterPage";

export const REGISTER_TAI_KHOAN_REQUEST = `${PREFIX}/REGISTER_TAI_KHOAN_REQUEST`;
export const REGISTER_TAI_KHOAN_SUCCESS = `${PREFIX}/REGISTER_TAI_KHOAN_SUCCESS`;
export const REGISTER_TAI_KHOAN_FAILURE = `${PREFIX}/REGISTER_TAI_KHOAN_FAILURE`;