const PREFIX = "Admin";

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";


export const IS_HIDE_MODAL_MOVIE = "IS_HIDE_MODAL_MOVIE";

export const GET_SEARCH_PHIM_VALUE = "GET_SEARCH_PHIM_VALUE";

export const GET_SEARCH_USER_VALUE = "GET_SEARCH_USER_VALUE";



