const PREFIX = "HomePage";

export const GET_MOVIE_LIST_REQUEST = `${PREFIX}/GET_MOVIE_LIST_REQUEST`;
export const GET_MOVIE_LIST_SUCCESS = `${PREFIX}/GET_MOVIE_LIST_SUCCESS`;
export const GET_MOVIE_LIST_FAILURE = `${PREFIX}/GET_MOVIE_LIST_FAILURE`;


export const GET_MOVIE_LIST_SAP_CHIEU_REQUEST = `${PREFIX}/GET_MOVIE_LIST_SAP_CHIEU_REQUEST`;
export const GET_MOVIE_LIST_SAP_CHIEU_SUCCESS = `${PREFIX}/GET_MOVIE_LIST_SAP_CHIEU_SUCCESS`;
export const GET_MOVIE_LIST_SAP_CHIEU_FAILURE = `${PREFIX}/GET_MOVIE_LIST_SAP_CHIEU_FAILURE`;


export const RENDER_DETAIL_PAGE_SAP_CHIEU = "RENDER_DETAIL_PAGE_SAP_CHIEU";

export const XEM_THEM_DIEN_ANH = "XEM_THEM_DIEN_ANH";
export const XEM_THEM_REVIEW = "XEM_THEM_REVIEW";
export const XEM_THEM_KHUYEN_MAI = "XEM_THEM_KHUYEN_MAI";


export const GET_THONG_TIN_HE_THONG_RAP_REQUEST = `${PREFIX}/GET_THONG_TIN_HE_THONG_RAP_REQUEST`;
export const GET_THONG_TIN_HE_THONG_RAP_SUCCESS = `${PREFIX}/GET_THONG_TIN_HE_THONG_RAP_SUCCESS`;
export const GET_THONG_TIN_HE_THONG_RAP_FAILURE = `${PREFIX}/GET_THONG_TIN_HE_THONG_RAP_FAILURE`;


export const GET_THONG_TIN_CUM_RAP_REQUEST = `${PREFIX}/GET_THONG_TIN_CUM_RAP_REQUEST`;
export const GET_THONG_TIN_CUM_RAP_SUCCESS = `${PREFIX}/GET_THONG_TIN_CUM_RAP_SUCCESS`;
export const GET_THONG_TIN_CUM_RAP_FAILURE = `${PREFIX}/GET_THONG_TIN_CUM_RAP_FAILURE`;


export const GET_THONG_TIN_LICH_CHIEU_REQUEST = `${PREFIX}/GET_THONG_TIN_LICH_CHIEU_REQUEST`;
export const GET_THONG_TIN_LICH_CHIEU_SUCCESS = `${PREFIX}/GET_THONG_TIN_LICH_CHIEU_SUCCESS`;
export const GET_THONG_TIN_LICH_CHIEU_FAILURE = `${PREFIX}/GET_THONG_TIN_LICH_CHIEU_FAILURE`;


export const GET_BANNER_REQUEST = `${PREFIX}/GET_BANNER_REQUEST`;
export const GET_BANNER_SUCCESS = `${PREFIX}/GET_BANNER_SUCCESS`;
export const GET_BANNER_FAILURE = `${PREFIX}/GET_BANNER_FAILURE`;


export const SET_THONG_TIN_VE = `${PREFIX}/SET_THONG_TIN_VE`;

export const SHOW_TRAILER = "SHOW_TRAILER"