const PREFIX = "DetailPage";

export const GET_MOVIE_DETAIL_REQUEST = `${PREFIX}/GET_MOVIE_DETAIL_REQUEST`;
export const GET_MOVIE_DETAIL_SUCCESS = `${PREFIX}/GET_MOVIE_DETAIL_SUCCESS`;
export const GET_MOVIE_DETAIL_FAILURE = `${PREFIX}/GET_MOVIE_DETAIL_FAILURE`;


export const XEM_THEM_FEEDBACK = "XEM_THEM_FEEDBACK"